In [ ]:
import pandas as pd

# Path to the CSV file
mc1_edges_file_path  = 'mc1_edges.csv'

# Read the CSV file into a DataFrame
mc1_edges_df = pd.read_csv(mc1_edges_file_path)
mc1_edges_df

              Edge Type  source  target  key
0      InterpolatesFrom       0    1841    0
1            RecordedBy       0       4    0
2           PerformerOf       1       0    0
3            ComposerOf       1   16180    0
4           PerformerOf       2       0    0
...                 ...     ...     ...  ...
37852        ComposerOf   17408   17111    0
37853        ComposerOf   17408   17112    0
37854        ComposerOf   17408   17113    0
37855       PerformerOf   17409   17411    0
37856  InterpolatesFrom   17411    9068    0

[37857 rows x 4 columns]

In [139]:
mc1_edges_df.iloc[17411]

Edge Type    InStyleOf
source            7271
target           11290
key                  0
Name: 17411, dtype: object

In [140]:
import pandas as pd

# Path to the CSV file
mc1_nodes_file_path = 'mc1_nodes.csv'

# Read the CSV file into a DataFrame
mc1_nodes_df = pd.read_csv(mc1_nodes_file_path)
mc1_nodes_df
mc1_nodes_df.iloc[17411]

Node Type                  Song
name              Tidal Whisper
single                     True
release_date             2033.0
genre              Oceanus Folk
notable                    True
id                        17411
written_date                NaN
stage_name                  NaN
notoriety_date           2033.0
Name: 17411, dtype: object

In [141]:
#Merging DataFrame

import pandas as pd

# Load your node and edge CSV files
nodes_df = pd.read_csv('mc1_nodes.csv')

edges_df = pd.read_csv('mc1_edges.csv')

# Merging the data on 'id' from nodes_df and 'source' from edges_df
merged_df = pd.merge(edges_df, nodes_df, left_on='source', right_on='id', how='left')


# Displaying the merged dataframe
merged_df

,Edge Type,source,target,key,Node Type,name,single,release_date,genre,notable,id,written_date,stage_name,notoriety_date
0,InterpolatesFrom,0,1841,0,Song,Breaking These Chains,True,2017.0,Oceanus Folk,True,0,NaN,NaN,NaN
1,RecordedBy,0,4,0,Song,Breaking These Chains,True,2017.0,Oceanus Folk,True,0,NaN,NaN,NaN
2,PerformerOf,1,0,0,Person,Carlos Duffy,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN
3,ComposerOf,1,16180,0,Person,Carlos Duffy,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN
4,PerformerOf,2,0,0,Person,Min Qin,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37852,ComposerOf,17408,17111,0,Person,Scarlett Moon,NaN,NaN,NaN,NaN,17408,NaN,NaN,NaN
37853,ComposerOf,17408,17112,0,Person,Scarlett Moon,NaN,NaN,NaN,NaN,17408,NaN,NaN,NaN
37854,ComposerOf,17408,17113,0,Person,Scarlett Moon,NaN,NaN,NaN,NaN,17408,NaN,NaN,NaN
37855,PerformerOf,17409,17411,0,Person,Isla Quinn,NaN,NaN,NaN,NaN,17409,NaN,NaN,NaN
37856,InterpolatesFrom,17411,9068,0,Song,Tidal Whisper,True,2033.0,Oceanus Folk,True,17411,NaN,NaN,2033.0

In [142]:
# Filter the rows where 'notable' is False
notable_false_df = merged_df[merged_df['notable'] == False]

# Display the filtered dataframe
notable_false_df

,Edge Type,source,target,key,Node Type,name,single,release_date,genre,notable,id,written_date,stage_name,notoriety_date
49,InterpolatesFrom,15,16367,0,Song,Sovereign Soul,True,2027.0,Darkwave,False,15,NaN,NaN,NaN
50,RecordedBy,15,24,0,Song,Sovereign Soul,True,2027.0,Darkwave,False,15,NaN,NaN,NaN
51,DistributedBy,15,21,0,Song,Sovereign Soul,True,2027.0,Darkwave,False,15,NaN,NaN,NaN
655,LyricalReferenceTo,233,15383,0,Song,"Boots, Dust, and True Love",True,2013.0,Doom Metal,False,233,NaN,NaN,NaN
656,RecordedBy,233,168,0,Song,"Boots, Dust, and True Love",True,2013.0,Doom Metal,False,233,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37548,LyricalReferenceTo,17307,17200,0,Song,Albatross,False,2001.0,Oceanus Folk,False,17307,NaN,NaN,NaN
37549,DirectlySamples,17308,8812,0,Song,By the Stars,False,2001.0,Oceanus Folk,False,17308,NaN,NaN,NaN
37616,InStyleOf,17333,4222,0,Song,The Undertow Waltz,False,2005.0,Oceanus Folk,False,17333,NaN,NaN,NaN
37617,LyricalReferenceTo,17338,3862,0,Song,Vanishing Point,False,2013.0,Oceanus Folk,False,17338,NaN,NaN,NaN
37618,LyricalReferenceTo,17339,5840,0,Song,The Sompass Spins,False,2013.0,Oceanus Folk,False,17339,NaN,NaN,NaN

In [143]:
# Filter the rows where 'notoriety_date' is not the same as 'release_date'
filtered_df = merged_df[merged_df['notoriety_date'] != merged_df['release_date']]

# Display the filtered dataframe
filtered_df

,Edge Type,source,target,key,Node Type,name,single,release_date,genre,notable,id,written_date,stage_name,notoriety_date
0,InterpolatesFrom,0,1841,0,Song,Breaking These Chains,True,2017.0,Oceanus Folk,True,0,NaN,NaN,NaN
1,RecordedBy,0,4,0,Song,Breaking These Chains,True,2017.0,Oceanus Folk,True,0,NaN,NaN,NaN
2,PerformerOf,1,0,0,Person,Carlos Duffy,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN
3,ComposerOf,1,16180,0,Person,Carlos Duffy,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN
4,PerformerOf,2,0,0,Person,Min Qin,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37851,LyricistOf,17407,17113,0,Person,Nate Wild,NaN,NaN,NaN,NaN,17407,NaN,NaN,NaN
37852,ComposerOf,17408,17111,0,Person,Scarlett Moon,NaN,NaN,NaN,NaN,17408,NaN,NaN,NaN
37853,ComposerOf,17408,17112,0,Person,Scarlett Moon,NaN,NaN,NaN,NaN,17408,NaN,NaN,NaN
37854,ComposerOf,17408,17113,0,Person,Scarlett Moon,NaN,NaN,NaN,NaN,17408,NaN,NaN,NaN
37855,PerformerOf,17409,17411,0,Person,Isla Quinn,NaN,NaN,NaN,NaN,17409,NaN,NaN,NaN

In [144]:
# Filter the rows where 'notoriety_date' is not empty (not NaN)
filtered_non_empty_notoriety = filtered_df[filtered_df['notoriety_date'].notna()]

# Display the filtered dataframe
filtered_non_empty_notoriety

,Edge Type,source,target,key,Node Type,name,single,release_date,genre,notable,id,written_date,stage_name,notoriety_date
5625,InStyleOf,2078,9647,0,Song,Dawning Breaths,False,2026.0,Indie Pop,True,2078,NaN,NaN,2029.0
5626,InterpolatesFrom,2078,15715,0,Song,Dawning Breaths,False,2026.0,Indie Pop,True,2078,NaN,NaN,2029.0
5627,CoverOf,2078,6946,0,Song,Dawning Breaths,False,2026.0,Indie Pop,True,2078,NaN,NaN,2029.0
5628,InStyleOf,2078,11363,0,Song,Dawning Breaths,False,2026.0,Indie Pop,True,2078,NaN,NaN,2029.0
5629,RecordedBy,2078,2081,0,Song,Dawning Breaths,False,2026.0,Indie Pop,True,2078,NaN,NaN,2029.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34467,DirectlySamples,16042,6551,0,Song,The Simple Truth Between Us,False,2023.0,Doom Metal,True,16042,2023.0,NaN,2026.0
34468,CoverOf,16042,4834,0,Song,The Simple Truth Between Us,False,2023.0,Doom Metal,True,16042,2023.0,NaN,2026.0
34469,CoverOf,16042,6006,0,Song,The Simple Truth Between Us,False,2023.0,Doom Metal,True,16042,2023.0,NaN,2026.0
34470,RecordedBy,16042,16047,0,Song,The Simple Truth Between Us,False,2023.0,Doom Metal,True,16042,2023.0,NaN,2026.0
34471,DistributedBy,16042,2791,0,Song,The Simple Truth Between Us,False,2023.0,Doom Metal,True,16042,2023.0,NaN,2026.0

In [145]:
# Dropping the 'source' and 'target' columns from the merged dataframe

import pandas as pd

merged_df_cleaned = merged_df.drop(columns=['source', 'target','key','id','stage_name'])
merged_df_cleaned.head(5)

,Edge Type,Node Type,name,single,release_date,genre,notable,written_date,notoriety_date
0,InterpolatesFrom,Song,Breaking These Chains,True,2017.0,Oceanus Folk,True,NaN,NaN
1,RecordedBy,Song,Breaking These Chains,True,2017.0,Oceanus Folk,True,NaN,NaN
2,PerformerOf,Person,Carlos Duffy,NaN,NaN,NaN,NaN,NaN,NaN
3,ComposerOf,Person,Carlos Duffy,NaN,NaN,NaN,NaN,NaN,NaN
4,PerformerOf,Person,Min Qin,NaN,NaN,NaN,NaN,NaN,NaN

In [146]:
#Fill Values from before until the next value changes
columns_to_fill = ['single', 'release_date', 'notable','genre']
merged_df_cleaned[columns_to_fill] = merged_df_cleaned[columns_to_fill].fillna(method='ffill')
#merged_df_cleaned.head(50)
merged_df_cleaned

/var/folders/vt/4_p12lhd54z540yzpj8py9qw0000gn/T/ipykernel_27054/2116587170.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  merged_df_cleaned[columns_to_fill] = merged_df_cleaned[columns_to_fill].fillna(method='ffill')
/var/folders/vt/4_p12lhd54z540yzpj8py9qw0000gn/T/ipykernel_27054/2116587170.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  merged_df_cleaned[columns_to_fill] = merged_df_cleaned[columns_to_fill].fillna(method='ffill')

,Edge Type,Node Type,name,single,release_date,genre,notable,written_date,notoriety_date
0,InterpolatesFrom,Song,Breaking These Chains,True,2017.0,Oceanus Folk,True,NaN,NaN
1,RecordedBy,Song,Breaking These Chains,True,2017.0,Oceanus Folk,True,NaN,NaN
2,PerformerOf,Person,Carlos Duffy,True,2017.0,Oceanus Folk,True,NaN,NaN
3,ComposerOf,Person,Carlos Duffy,True,2017.0,Oceanus Folk,True,NaN,NaN
4,PerformerOf,Person,Min Qin,True,2017.0,Oceanus Folk,True,NaN,NaN
...,...,...,...,...,...,...,...,...,...
37852,ComposerOf,Person,Scarlett Moon,False,2035.0,Oceanus Folk,True,NaN,NaN
37853,ComposerOf,Person,Scarlett Moon,False,2035.0,Oceanus Folk,True,NaN,NaN
37854,ComposerOf,Person,Scarlett Moon,False,2035.0,Oceanus Folk,True,NaN,NaN
37855,PerformerOf,Person,Isla Quinn,False,2035.0,Oceanus Folk,True,NaN,NaN
37856,InterpolatesFrom,Song,Tidal Whisper,True,2033.0,Oceanus Folk,True,NaN,2033.0

In [147]:
# Apply the condition: Replace NaN in 'notoriety_date' with 'release_date' if 'release_date' >= 'notoriety_date'
merged_df_cleaned['notoriety_date'] = merged_df_cleaned.apply(
    lambda row: row['release_date'] if pd.isna(row['notoriety_date']) and row['release_date'] >= row['release_date'] else row['notoriety_date'],
    axis=1
)

# Display the first 50 rows of the cleaned dataframe
#merged_df_cleaned.head(50)
merged_df_cleaned

,Edge Type,Node Type,name,single,release_date,genre,notable,written_date,notoriety_date
0,InterpolatesFrom,Song,Breaking These Chains,True,2017.0,Oceanus Folk,True,NaN,2017.0
1,RecordedBy,Song,Breaking These Chains,True,2017.0,Oceanus Folk,True,NaN,2017.0
2,PerformerOf,Person,Carlos Duffy,True,2017.0,Oceanus Folk,True,NaN,2017.0
3,ComposerOf,Person,Carlos Duffy,True,2017.0,Oceanus Folk,True,NaN,2017.0
4,PerformerOf,Person,Min Qin,True,2017.0,Oceanus Folk,True,NaN,2017.0
...,...,...,...,...,...,...,...,...,...
37852,ComposerOf,Person,Scarlett Moon,False,2035.0,Oceanus Folk,True,NaN,2035.0
37853,ComposerOf,Person,Scarlett Moon,False,2035.0,Oceanus Folk,True,NaN,2035.0
37854,ComposerOf,Person,Scarlett Moon,False,2035.0,Oceanus Folk,True,NaN,2035.0
37855,PerformerOf,Person,Isla Quinn,False,2035.0,Oceanus Folk,True,NaN,2035.0
37856,InterpolatesFrom,Song,Tidal Whisper,True,2033.0,Oceanus Folk,True,NaN,2033.0

In [148]:
# Replace NaN values in 'written_date' with the corresponding value from 'release_date'
merged_df_cleaned['written_date'] = merged_df_cleaned['written_date'].fillna(merged_df_cleaned['release_date'])

# Display the modified dataframe
merged_df_cleaned.head(50)
#merged_df_cleaned

,Edge Type,Node Type,name,single,release_date,genre,notable,written_date,notoriety_date
0,InterpolatesFrom,Song,Breaking These Chains,True,2017.0,Oceanus Folk,True,2017.0,2017.0
1,RecordedBy,Song,Breaking These Chains,True,2017.0,Oceanus Folk,True,2017.0,2017.0
2,PerformerOf,Person,Carlos Duffy,True,2017.0,Oceanus Folk,True,2017.0,2017.0
3,ComposerOf,Person,Carlos Duffy,True,2017.0,Oceanus Folk,True,2017.0,2017.0
4,PerformerOf,Person,Min Qin,True,2017.0,Oceanus Folk,True,2017.0,2017.0
5,ProducerOf,Person,Min Qin,True,2017.0,Oceanus Folk,True,2017.0,2017.0
6,PerformerOf,Person,Xiuying Xie,True,2017.0,Oceanus Folk,True,2017.0,2017.0
7,InterpolatesFrom,Song,Unshackled Heart,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
8,InStyleOf,Song,Unshackled Heart,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
9,InterpolatesFrom,Song,Unshackled Heart,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
10,LyricalReferenceTo,Song,Unshackled Heart,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
11,CoverOf,Song,Unshackled Heart,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
12,InStyleOf,Song,Unshackled Heart,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
13,InStyleOf,Song,Unshackled Heart,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
14,InterpolatesFrom,Song,Unshackled Heart,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
15,InterpolatesFrom,Song,Unshackled Heart,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
16,InterpolatesFrom,Song,Unshackled Heart,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
17,InStyleOf,Song,Unshackled Heart,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
18,CoverOf,Song,Unshackled Heart,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
19,InStyleOf,Song,Unshackled Heart,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
20,DistributedBy,Song,Unshackled Heart,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
21,ComposerOf,Person,Luke Payne,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
22,MemberOf,Person,Xiulan Zeng,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
23,PerformerOf,Person,Xiulan Zeng,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
24,PerformerOf,Person,Xiulan Zeng,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
25,LyricistOf,Person,Xiulan Zeng,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
26,PerformerOf,Person,Xiulan Zeng,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
27,PerformerOf,Person,Xiulan Zeng,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
28,LyricistOf,Person,Xiulan Zeng,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
29,PerformerOf,Person,Xiulan Zeng,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
30,PerformerOf,Person,Xiulan Zeng,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
31,ProducerOf,Person,Xiulan Zeng,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
32,ProducerOf,Person,Xiulan Zeng,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
33,PerformerOf,Person,Xiulan Zeng,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
34,MemberOf,Person,David Franklin,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
35,PerformerOf,Person,David Franklin,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
36,PerformerOf,Person,David Franklin,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
37,LyricistOf,Person,David Franklin,False,2026.0,Lo-Fi Electronica,True,2026.0,2026.0
38,InterpolatesFrom,Song,No Limits Left,True,2020.0,Indie Folk,True,2020.0,2020.0
39,RecordedBy,Song,No Limits Left,True,2020.0,Indie Folk,True,2020.0,2020.0
40,ProducerOf,Person,Gang Long,True,2020.0,Indie Folk,True,2020.0,2020.0
41,ProducerOf,Person,Gang Long,True,2020.0,Indie Folk,True,2020.0,2020.0
42,ProducerOf,Person,Gang Long,True,2020.0,Indie Folk,True,2020.0,2020.0
43,ComposerOf,Person,Yong Yi,True,2020.0,Indie Folk,True,2020.0,2020.0
44,ComposerOf,Person,Yong Yi,True,2020.0,Indie Folk,True,2020.0,2020.0
45,LyricistOf,Person,Li Yi,True,2020.0,Indie Folk,True,2020.0,2020.0
46,PerformerOf,Person,Li Yi,True,2020.0,Indie Folk,True,2020.0,2020.0
47,LyricistOf,Person,Li Yi,True,2020.0,Indie Folk,True,2020.0,2020.0
48,PerformerOf,Person,Li Yi,True,2020.0,Indie Folk,True,2020.0,2020.0
49,InterpolatesFrom,Song,Sovereign Soul,True,2027.0,Darkwave,False,2027.0,2027.0

In [157]:
# Convert the 'release_date', 'written_date', and 'notoriety_date' columns to integer year
merged_df_cleaned['release_date'] = merged_df_cleaned['release_date'].astype('Int64')
merged_df_cleaned['written_date'] = merged_df_cleaned['written_date'].astype('Int64')
merged_df_cleaned['notoriety_date'] = merged_df_cleaned['notoriety_date'].astype('Int64')

# Display the updated dataframe
merged_df_cleaned.head(50)

,Edge Type,Node Type,name,single,release_date,genre,notable,written_date,notoriety_date
0,InterpolatesFrom,Song,Breaking These Chains,True,2017,Oceanus Folk,True,2017,2017
1,RecordedBy,Song,Breaking These Chains,True,2017,Oceanus Folk,True,2017,2017
2,PerformerOf,Person,Carlos Duffy,True,2017,Oceanus Folk,True,2017,2017
3,ComposerOf,Person,Carlos Duffy,True,2017,Oceanus Folk,True,2017,2017
4,PerformerOf,Person,Min Qin,True,2017,Oceanus Folk,True,2017,2017
5,ProducerOf,Person,Min Qin,True,2017,Oceanus Folk,True,2017,2017
6,PerformerOf,Person,Xiuying Xie,True,2017,Oceanus Folk,True,2017,2017
7,InterpolatesFrom,Song,Unshackled Heart,False,2026,Lo-Fi Electronica,True,2026,2026
8,InStyleOf,Song,Unshackled Heart,False,2026,Lo-Fi Electronica,True,2026,2026
9,InterpolatesFrom,Song,Unshackled Heart,False,2026,Lo-Fi Electronica,True,2026,2026
10,LyricalReferenceTo,Song,Unshackled Heart,False,2026,Lo-Fi Electronica,True,2026,2026
11,CoverOf,Song,Unshackled Heart,False,2026,Lo-Fi Electronica,True,2026,2026
12,InStyleOf,Song,Unshackled Heart,False,2026,Lo-Fi Electronica,True,2026,2026
13,InStyleOf,Song,Unshackled Heart,False,2026,Lo-Fi Electronica,True,2026,2026
14,InterpolatesFrom,Song,Unshackled Heart,False,2026,Lo-Fi Electronica,True,2026,2026
15,InterpolatesFrom,Song,Unshackled Heart,False,2026,Lo-Fi Electronica,True,2026,2026
16,InterpolatesFrom,Song,Unshackled Heart,False,2026,Lo-Fi Electronica,True,2026,2026
17,InStyleOf,Song,Unshackled Heart,False,2026,Lo-Fi Electronica,True,2026,2026
18,CoverOf,Song,Unshackled Heart,False,2026,Lo-Fi Electronica,True,2026,2026
19,InStyleOf,Song,Unshackled Heart,False,2026,Lo-Fi Electronica,True,2026,2026
20,DistributedBy,Song,Unshackled Heart,False,2026,Lo-Fi Electronica,True,2026,2026
21,ComposerOf,Person,Luke Payne,False,2026,Lo-Fi Electronica,True,2026,2026
22,MemberOf,Person,Xiulan Zeng,False,2026,Lo-Fi Electronica,True,2026,2026
23,PerformerOf,Person,Xiulan Zeng,False,2026,Lo-Fi Electronica,True,2026,2026
24,PerformerOf,Person,Xiulan Zeng,False,2026,Lo-Fi Electronica,True,2026,2026
25,LyricistOf,Person,Xiulan Zeng,False,2026,Lo-Fi Electronica,True,2026,2026
26,PerformerOf,Person,Xiulan Zeng,False,2026,Lo-Fi Electronica,True,2026,2026
27,PerformerOf,Person,Xiulan Zeng,False,2026,Lo-Fi Electronica,True,2026,2026
28,LyricistOf,Person,Xiulan Zeng,False,2026,Lo-Fi Electronica,True,2026,2026
29,PerformerOf,Person,Xiulan Zeng,False,2026,Lo-Fi Electronica,True,2026,2026
30,PerformerOf,Person,Xiulan Zeng,False,2026,Lo-Fi Electronica,True,2026,2026
31,ProducerOf,Person,Xiulan Zeng,False,2026,Lo-Fi Electronica,True,2026,2026
32,ProducerOf,Person,Xiulan Zeng,False,2026,Lo-Fi Electronica,True,2026,2026
33,PerformerOf,Person,Xiulan Zeng,False,2026,Lo-Fi Electronica,True,2026,2026
34,MemberOf,Person,David Franklin,False,2026,Lo-Fi Electronica,True,2026,2026
35,PerformerOf,Person,David Franklin,False,2026,Lo-Fi Electronica,True,2026,2026
36,PerformerOf,Person,David Franklin,False,2026,Lo-Fi Electronica,True,2026,2026
37,LyricistOf,Person,David Franklin,False,2026,Lo-Fi Electronica,True,2026,2026
38,InterpolatesFrom,Song,No Limits Left,True,2020,Indie Folk,True,2020,2020
39,RecordedBy,Song,No Limits Left,True,2020,Indie Folk,True,2020,2020
40,ProducerOf,Person,Gang Long,True,2020,Indie Folk,True,2020,2020
41,ProducerOf,Person,Gang Long,True,2020,Indie Folk,True,2020,2020
42,ProducerOf,Person,Gang Long,True,2020,Indie Folk,True,2020,2020
43,ComposerOf,Person,Yong Yi,True,2020,Indie Folk,True,2020,2020
44,ComposerOf,Person,Yong Yi,True,2020,Indie Folk,True,2020,2020
45,LyricistOf,Person,Li Yi,True,2020,Indie Folk,True,2020,2020
46,PerformerOf,Person,Li Yi,True,2020,Indie Folk,True,2020,2020
47,LyricistOf,Person,Li Yi,True,2020,Indie Folk,True,2020,2020
48,PerformerOf,Person,Li Yi,True,2020,Indie Folk,True,2020,2020
49,InterpolatesFrom,Song,Sovereign Soul,True,2027,Darkwave,False,2027,2027

### TestCodes

In [150]:
# Filter the rows where 'notoriety_date' is not equal to 'release_date'
filtered_diff_dates = merged_df_cleaned[merged_df_cleaned['notoriety_date'] != merged_df_cleaned['release_date']]

# Display the filtered dataframe
filtered_diff_dates

,Edge Type,Node Type,name,single,release_date,genre,notable,written_date,notoriety_date
5625,InStyleOf,Song,Dawning Breaths,False,2026.0,Indie Pop,True,2026.0,2029.0
5626,InterpolatesFrom,Song,Dawning Breaths,False,2026.0,Indie Pop,True,2026.0,2029.0
5627,CoverOf,Song,Dawning Breaths,False,2026.0,Indie Pop,True,2026.0,2029.0
5628,InStyleOf,Song,Dawning Breaths,False,2026.0,Indie Pop,True,2026.0,2029.0
5629,RecordedBy,Song,Dawning Breaths,False,2026.0,Indie Pop,True,2026.0,2029.0
...,...,...,...,...,...,...,...,...,...
34467,DirectlySamples,Song,The Simple Truth Between Us,False,2023.0,Doom Metal,True,2023.0,2026.0
34468,CoverOf,Song,The Simple Truth Between Us,False,2023.0,Doom Metal,True,2023.0,2026.0
34469,CoverOf,Song,The Simple Truth Between Us,False,2023.0,Doom Metal,True,2023.0,2026.0
34470,RecordedBy,Song,The Simple Truth Between Us,False,2023.0,Doom Metal,True,2023.0,2026.0
34471,DistributedBy,Song,The Simple Truth Between Us,False,2023.0,Doom Metal,True,2023.0,2026.0

In [151]:
# Filter the rows where 'notoriety_date' is greater than 'release_date'
filtered_notoriety_greater_than_release = merged_df_cleaned[merged_df_cleaned['notoriety_date'] > merged_df_cleaned['release_date']]

# Display the filtered dataframe
filtered_notoriety_greater_than_release.head(5)

,Edge Type,Node Type,name,single,release_date,genre,notable,written_date,notoriety_date
5625,InStyleOf,Song,Dawning Breaths,False,2026.0,Indie Pop,True,2026.0,2029.0
5626,InterpolatesFrom,Song,Dawning Breaths,False,2026.0,Indie Pop,True,2026.0,2029.0
5627,CoverOf,Song,Dawning Breaths,False,2026.0,Indie Pop,True,2026.0,2029.0
5628,InStyleOf,Song,Dawning Breaths,False,2026.0,Indie Pop,True,2026.0,2029.0
5629,RecordedBy,Song,Dawning Breaths,False,2026.0,Indie Pop,True,2026.0,2029.0

In [152]:
# Filter the rows where 'written_date' is not NaN
filtered_written_date_not_na = merged_df_cleaned[merged_df_cleaned['written_date'].notna()]

# Display the filtered dataframe
filtered_written_date_not_na.head(5)

,Edge Type,Node Type,name,single,release_date,genre,notable,written_date,notoriety_date
0,InterpolatesFrom,Song,Breaking These Chains,True,2017.0,Oceanus Folk,True,2017.0,2017.0
1,RecordedBy,Song,Breaking These Chains,True,2017.0,Oceanus Folk,True,2017.0,2017.0
2,PerformerOf,Person,Carlos Duffy,True,2017.0,Oceanus Folk,True,2017.0,2017.0
3,ComposerOf,Person,Carlos Duffy,True,2017.0,Oceanus Folk,True,2017.0,2017.0
4,PerformerOf,Person,Min Qin,True,2017.0,Oceanus Folk,True,2017.0,2017.0

In [153]:
# Filter the rows where 'written_date' is less than 'release_date'
filtered_written_less_than_release = merged_df_cleaned[merged_df_cleaned['written_date'] == merged_df_cleaned['release_date']]

# Display the filtered dataframe
filtered_written_less_than_release

,Edge Type,Node Type,name,single,release_date,genre,notable,written_date,notoriety_date
0,InterpolatesFrom,Song,Breaking These Chains,True,2017.0,Oceanus Folk,True,2017.0,2017.0
1,RecordedBy,Song,Breaking These Chains,True,2017.0,Oceanus Folk,True,2017.0,2017.0
2,PerformerOf,Person,Carlos Duffy,True,2017.0,Oceanus Folk,True,2017.0,2017.0
3,ComposerOf,Person,Carlos Duffy,True,2017.0,Oceanus Folk,True,2017.0,2017.0
4,PerformerOf,Person,Min Qin,True,2017.0,Oceanus Folk,True,2017.0,2017.0
...,...,...,...,...,...,...,...,...,...
37852,ComposerOf,Person,Scarlett Moon,False,2035.0,Oceanus Folk,True,2035.0,2035.0
37853,ComposerOf,Person,Scarlett Moon,False,2035.0,Oceanus Folk,True,2035.0,2035.0
37854,ComposerOf,Person,Scarlett Moon,False,2035.0,Oceanus Folk,True,2035.0,2035.0
37855,PerformerOf,Person,Isla Quinn,False,2035.0,Oceanus Folk,True,2035.0,2035.0
37856,InterpolatesFrom,Song,Tidal Whisper,True,2033.0,Oceanus Folk,True,2033.0,2033.0

In [154]:
# # Filter the rows where 'stage_name' is not NaN
# filtered_stage_name_not_na = merged_df_cleaned[merged_df_cleaned['stage_name'].notna()]

# # Display the filtered dataframe
# filtered_stage_name_not_na.head(50)

#Column has been dropped.

In [155]:
# Filter rows where 'name' is 'Carlos Duffy'
carlos_duffy_data = merged_df_cleaned[merged_df_cleaned['name'] == 'Carlos Duffy']

# Display the rows containing information about Carlos Duffy
carlos_duffy_data

,Edge Type,Node Type,name,single,release_date,genre,notable,written_date,notoriety_date
2,PerformerOf,Person,Carlos Duffy,True,2017.0,Oceanus Folk,True,2017.0,2017.0
3,ComposerOf,Person,Carlos Duffy,True,2017.0,Oceanus Folk,True,2017.0,2017.0

In [158]:
# Check the data types of all columns in the DataFrame
column_data_types = merged_df_cleaned.dtypes

# Display the data types
column_data_types

Edge Type         object
Node Type         object
name              object
single              bool
release_date       Int64
genre             object
notable             bool
written_date       Int64
notoriety_date     Int64
dtype: object